# 01 Data Types and Data Structures

## Basic variable types

String concatenation, is done with the + operator.

Datatype of a variable can be determined by using the type() function.

Datatypes are:
- `int`, `float`, `bool`, `str`, `list`, `tuple`, `dict`, `set`, `None`

Datatypes can be converted to each other using the following functions:

- `int(x)`, `float(x)`, `bool(x)`, `str(x)`, `list(x)`, `tuple(x)`, `dict(x)`, `set(x)`

In [82]:
# String creation with single and double quotes
string_welcome = "Welcome to the"
string_name = 'Algorithms class'
string_num = "101"
# String concatenation
string_welcome_name = string_welcome + " " + string_name + " " + string_num
print(string_welcome_name)
# Data type visualisation
print(type(string_welcome_name), string_welcome_name)
print(type(string_num), string_num)
# Data type conversion
my_num_int = int(string_num)
print(type(my_num_int), str(my_num_int))

my_num_float = float(string_num)
print(type(my_num_float), str(my_num_float))

my_bool = False
print(type(my_bool), str(my_bool))

Welcome to the Algorithms class 101
<class 'str'> Welcome to the Algorithms class 101
<class 'str'> 101
<class 'int'> 101
<class 'float'> 101.0
<class 'bool'> False


## Basic Math Operations
Python has a built-in math module with many functions.
The basic math operations are:
- `+`, `-`, `*`, `/`, `//`, `%`, `**`
- addition, subtraction, multiplication, division, floor division, modulo, power

In [83]:
# Some math examples
print("7 + 3 = ", 7 + 3)
print("7 - 3 = ", 7 - 3)
print("7 * 3 = ", 7 * 3)
print("7 / 3 = ", 7 / 3)
print("7 // 3 = ", 7 // 3)
print("7 % 3 = ", 7 % 3)
print("7 ** 3 = ", 7 ** 3)
# It is possible to use the variables
a = 8
b = 3
print("a + b = ", a + b)
# And use multiple operations
print("a + b * b = ", a + b * b)

7 + 3 =  10
7 - 3 =  4
7 * 3 =  21
7 / 3 =  2.3333333333333335
7 // 3 =  2
7 % 3 =  1
7 ** 3 =  343
a + b =  11
a + b * b =  17


## Data Collections
Python has different data structures:
- `list`, `tuple`, `dict`, `set`
Unlike other languages the datatype of the variables inside this data structures is not specified, and could be different for each variable.

### **List:** ordered collection of items. Use with square brackets. a = [1, 2, 3]

In [84]:
# List creation
my_list = [1, 2, 3, 4, 5]
print("my_list = ", my_list, "length = ", len(my_list), "type = ", type(my_list))
# List indexing
print("my_list[2] = ", my_list[2])
# List multiple data types
my_list_2 = [1, 2, 3, 4, 5, "a", "b", "c"]
print("my_list_2 = ", my_list_2, "length = ", len(my_list_2), "type = ", type(my_list_2))
# List slicing
print("my_list_2[2:5] = ", my_list_2[2:5])
# List concatenation
my_list_3 = my_list + my_list_2
print("my_list + my_list_2 = ", my_list_3, "length = ", len(my_list_3), "type = ", type(my_list_3))
# List modification
# append, insert, remove, pop, clear, list[index] = value

my_list =  [1, 2, 3, 4, 5] length =  5 type =  <class 'list'>
my_list[2] =  3
my_list_2 =  [1, 2, 3, 4, 5, 'a', 'b', 'c'] length =  8 type =  <class 'list'>
my_list_2[2:5] =  [3, 4, 5]
my_list + my_list_2 =  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 'a', 'b', 'c'] length =  13 type =  <class 'list'>


### **Tuple:** ordered collection of items. Use with parentheses. a = (1, 2, 3)

In [85]:
# Tuples creation
my_tuple = (1, 2, 3, 4, 5)
print("my_tuple = ", my_tuple, "length = ", len(my_tuple), "type = ", type(my_tuple))
# Tuples indexing
print("my_tuple[2] = ", my_tuple[2])
# Tuples multiple data types
my_tuple_2 = (1, 2, 3, 4, 5, "a", "b", "c")
print("my_tuple_2 = ", my_tuple_2, "length = ", len(my_tuple_2), "type = ", type(my_tuple_2))
# Tuples slicing
print("my_tuple_2[2:5] = ", my_tuple_2[2:5])
# Tuples concatenation
my_tuple_3 = my_tuple + my_tuple_2
print("my_tuple + my_tuple_2 = ", my_tuple_3, "length = ", len(my_tuple_3), "type = ", type(my_tuple_3))
# Tuples are immutable
# one workaround is to convert the tuple to list modify it and convert back to tuple
my_tuple_4 = list(my_tuple)
my_tuple_4[2] = "a"
my_tuple_4 = tuple(my_tuple_4)
print("my_tuple_4 = ", my_tuple_4, "length = ", len(my_tuple_4), "type = ", type(my_tuple_4))

my_tuple =  (1, 2, 3, 4, 5) length =  5 type =  <class 'tuple'>
my_tuple[2] =  3
my_tuple_2 =  (1, 2, 3, 4, 5, 'a', 'b', 'c') length =  8 type =  <class 'tuple'>
my_tuple_2[2:5] =  (3, 4, 5)
my_tuple + my_tuple_2 =  (1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 'a', 'b', 'c') length =  13 type =  <class 'tuple'>
my_tuple_4 =  (1, 2, 'a', 4, 5) length =  5 type =  <class 'tuple'>


### **Dict:** unordered collection of key-value pairs. Use with curly brackets. a = {'a': 1, 'b': 2}

In [86]:
# Dictionaries creation
my_dict = {'a': 1, 'b': 2, 'c': 3}
print("my_dict = ", my_dict, "length = ", len(my_dict), "type = ", type(my_dict))
# Dictionaries indexing
print("my_dict['a'] = ", my_dict['a'])
# Dictionaries multiple data types
my_dict_2 = {'a': 1, 'b': 2, 'c': 3, 'd': "a", 'e': "b", 'f': "c"}
print("my_dict_2 = ", my_dict_2, "length = ", len(my_dict_2), "type = ", type(my_dict_2))
# Dictionaries slicing is not possible
# Dictionaries concatenation is not possible
# Dictionaries modification
# update, pop, clear, dict[key] = value

my_dict =  {'a': 1, 'b': 2, 'c': 3} length =  3 type =  <class 'dict'>
my_dict['a'] =  1
my_dict_2 =  {'a': 1, 'b': 2, 'c': 3, 'd': 'a', 'e': 'b', 'f': 'c'} length =  6 type =  <class 'dict'>


### **Set:** unordered collection of unique items. Use with curly brackets. a = {1, 2, 3}

In [87]:
# Sets creation
my_set = {1, 2, 3, 4, 5}
print("my_set = ", my_set, "length = ", len(my_set), "type = ", type(my_set))
# Sets indexing is not possible
# Sets multiple data types
my_set_2 = {1, 2, 3, 4, 5, "a", "b", "c"}
print("my_set_2 = ", my_set_2, "length = ", len(my_set_2), "type = ", type(my_set_2))
# Sets slicing is not possible
# Sets concatenation is not possible
# Sets modification
# add, remove, clear, set[index] = value

my_set =  {1, 2, 3, 4, 5} length =  5 type =  <class 'set'>
my_set_2 =  {1, 2, 3, 4, 5, 'b', 'c', 'a'} length =  8 type =  <class 'set'>


## Common String Operations
Some string operations are:
slicing, concatenation, repetition, comparison, formatting, and more.

In [88]:
# String slicing
string_operations = "abcdefghijklmnopqrstuvwxyz"
print("string_operations = ", string_operations, "length = ", len(string_operations), "type = ", type(string_operations))
print("string_operations[2:5] = ", string_operations[2:5])
print("string_operations[2:] = ", string_operations[2:])
print("string_operations[:5] = ", string_operations[:5])
print("string_operations[:] = ", string_operations[:])
print("string_operations[-5:] = ", string_operations[-5:])
print()
# String concatenation already explained
# String split
print("string_operations.split('c') = ", string_operations.split('c'))
# String count find and replace
print("count how many 'c' are in the string → ", string_operations.count('c'))
print("find index of 'c' → ", string_operations.find('c'))
print("replace the first 'a' with 'x' → ", string_operations.replace('a', 'x'))
print()
# String formatting
hours = 10
minutes = 9
seconds = 8
print("%02d:%02d:%02d → ", "%02d:%02d:%02d" % (hours, minutes, seconds))
# using the format method
print("'{}:{}:{}'.format(hours,minutes,seconds) → ", "{}:{}:{}".format(hours, minutes, seconds), end="")

string_operations =  abcdefghijklmnopqrstuvwxyz length =  26 type =  <class 'str'>
string_operations[2:5] =  cde
string_operations[2:] =  cdefghijklmnopqrstuvwxyz
string_operations[:5] =  abcde
string_operations[:] =  abcdefghijklmnopqrstuvwxyz
string_operations[-5:] =  vwxyz

string_operations.split('c') =  ['ab', 'defghijklmnopqrstuvwxyz']
count how many 'c' are in the string →  1
find index of 'c' →  2
replace the first 'a' with 'x' →  xbcdefghijklmnopqrstuvwxyz

%02d:%02d:%02d →  10:09:08
'{}:{}:{}'.format(hours,minutes,seconds) →  10:9:8

# 02 Logical Operators and Loops
## Logical Operators
Logical operators are &&, ||, and !

In [89]:
a = 1
b = 2
print("a = {}, b = {}".format(a, b))
print("a == b → ", a == b) # False
print("a != b → ", a != b) # True
print("a < b → ", a < b) # True
print("a > b → ", a > b) # False
print("a <= b → ", a <= b) # True
print("a >= b → ", a >= b) # False
print()
# Combining operation results
print("a == b and a < b", a == b and a < b) # False
print("a == b or a < b", a == b or a < b) # True
print("not a == b", not a == b) # True
print()

a = 1, b = 2
a == b →  False
a != b →  True
a < b →  True
a > b →  False
a <= b →  True
a >= b →  False

a == b and a < b False
a == b or a < b True
not a == b True



## If Statements

In [90]:
if a == b:
    print("a == b")
elif a < b:
    print("a < b")
else:
    print("a != b")
# a == b → False and a < b → True, a != b → True, so the value printed is a < b as it runs in order of the if statements

a < b


## Loop Structure
### While Loop

In [91]:
i = 5
while i > 0:
    print(i, end=" ")
    i -= 1
# it will print 5, 4, 3, 2, 1

5 4 3 2 1 

### For Loop

In [92]:
# for loop with range and list
list_1 = ['a', 'b', 'c', 'd', 'e']
for i in range(len(list_1)):
    print(list_1[i], end=" ")
# it will print a, b, c, d, e

a b c d e 

### Break and Continue
The break statement ends the loop.

The continue statement skips the rest of the current iteration.

In [93]:
# The loop can be breaked out with the break statement
list_1 = ['a', 'b', 'c', 'd', 'e']
for i in range(len(list_1)):
    if i == 2:
        break
    print(list_1[i], end=" ")
# it will print a, b
print()
# The loop can be continued with the continue statement
list_1 = ['a', 'b', 'c', 'd', 'e']
for i in range(len(list_1)):
    if i == 2:
        continue
    print(list_1[i], end=" ")
# it will print a, b, d, e
print()

# an example of a for loop using break and continue
list_random_words = ['hello', 'world', 'python', 'is', 'awesome', 'and', 'I', 'love', 'it']
for i in range(len(list_random_words)):
    if list_random_words[i] == 'I': # this part breaks the loop at the first 'I'
        break
    if len(list_random_words[i]) < 3: # this part skips the words with less than 3 characters → 'is' 'I' 'it'
        continue
    print(list_random_words[i], end=" ")
# it will print → hello world python awesome and

a b 
a b d e 
hello world python awesome and 

## List Comprehension

In [94]:
# an example of a list where all the elements are store in other but times 2
list_1 = [1, 2, 3, 4, 5]
list_2 = [i * 2 for i in list_1]
print("list = ", list_2)
# an example were only the words longer than 3 characters are stored in a new list
list_1 = ['hello', 'world', 'python', 'is', 'awesome', 'and', 'I', 'love', 'it']
list_2 = [i for i in list_1 if len(i) > 3]
print("list = ", list_2)

list =  [2, 4, 6, 8, 10]
list =  ['hello', 'world', 'python', 'awesome', 'love']


# 03 Functions and Objective-Oriented Programming
## Functions

In [95]:
def hello_world():
    print("hello world")
hello_world()

# function with arguments
def new_function(x, y):
    if x > y:
        return x + y
    else:
        return x - y
print("new_function(5, 3) = ", new_function(5, 3))
print("new_function(5, 8) = ", new_function(5, 8 ))


hello world
new_function(5, 3) =  8
new_function(5, 8) =  -3


## Built-in Functions
some built-in functions are:
- range() len() min() max() sum() print() input() map() ...

In [96]:
# Some examples of built-in functions
# range() len() min() max() sum() print() input() map() ...
range_1 = range(10)
print("range_1 = ", range_1)
print("len(range_1) = ", len(range_1))
print("min(range_1) = ", min(range_1))
print("max(range_1) = ", max(range_1))
print("sum(range_1) = ", sum(range_1))
print("print(range_1) = ", print(range_1)) # the print function returns None
print() # the input function returns the input of the user as a string

# example of map, sorted and filter
list_1 = [2,9,6,45,35,74,1,8,3,4]
print("list_1 → ", list_1)
print("sorted(list_1) → ", sorted(list_1))
print("map all elements * 2 and sort → ", list(map(lambda x: x * 2, list_1)))
print("filter only the element where x % 2 == 0 → ", list(filter(lambda x: x % 2 == 0, list_1)))

# example of sort list of tuples where the last element is the key
list_tuples = [(12,16,3),(2,5,9),(1,4,8),(3,6,7)]
print("list_tuples → ", list_tuples)
print("sorted(list_tuples, key=lambda x: x[2]) → ", sorted(list_tuples, key=lambda x: x[2]))

range_1 =  range(0, 10)
len(range_1) =  10
min(range_1) =  0
max(range_1) =  9
sum(range_1) =  45
range(0, 10)
print(range_1) =  None

list_1 →  [2, 9, 6, 45, 35, 74, 1, 8, 3, 4]
sorted(list_1) →  [1, 2, 3, 4, 6, 8, 9, 35, 45, 74]
map all elements * 2 and sort →  [4, 18, 12, 90, 70, 148, 2, 16, 6, 8]
filter only the element where x % 2 == 0 →  [2, 6, 74, 8, 4]
list_tuples →  [(12, 16, 3), (2, 5, 9), (1, 4, 8), (3, 6, 7)]
sorted(list_tuples, key=lambda x: x[2]) →  [(12, 16, 3), (3, 6, 7), (1, 4, 8), (2, 5, 9)]


## Object-Oriented Programming
### Class

In [97]:
# example of class
class Office:
    def __init__(self, name, location):
        self.name = name
        self.location = location
    def to_string(self):
        return "Office name: " + self.name + ", Location: " + self.location
    def change_location(self, new_location):
        self.location = new_location
office_1 = Office("Office 1", "New York")
office_2 = Office("Office 2", "Los Angeles")
print("office_1 → ", office_1.to_string())
print("office_2 → ", office_2.to_string())
print()
office_1.change_location("Chicago")
print("office_1 → ", office_1.to_string())
print("office_2 → ", office_2.to_string())
print()
office_1.name = "Office 1*"
print("office_1 → ", office_1.to_string())
print("office_2 → ", office_2.to_string())
dir(office_1) # shows the attributes of the class Office


office_1 →  Office name: Office 1, Location: New York
office_2 →  Office name: Office 2, Location: Los Angeles

office_1 →  Office name: Office 1, Location: Chicago
office_2 →  Office name: Office 2, Location: Los Angeles

office_1 →  Office name: Office 1*, Location: Chicago
office_2 →  Office name: Office 2, Location: Los Angeles


['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'change_location',
 'location',
 'name',
 'to_string']

### Inheritance

In [98]:
# Inheritance
class mini_office(Office): # the office class is inherited
    def __init__(self, name, location, size):
        super().__init__(name, location)
        self.size = size
    def to_string(self): # this method overrides the to_string method of the parent class
        return "Office name: " + self.name + ", Location: " + self.location + ", Size: " + self.size
mini_office_1 = mini_office("Office 1", "New York", "small")
mini_office_2 = mini_office("Office 2", "Los Angeles", "medium")
print("mini_office_1 → ", mini_office_1.to_string())
print("mini_office_2 → ", mini_office_2.to_string())
print()
mini_office_1.change_location("Chicago") # the change_location method is inherited from the office class
print("mini_office_1 → ", mini_office_1.to_string())
print("mini_office_2 → ", mini_office_2.to_string())
print()

mini_office_1 →  Office name: Office 1, Location: New York, Size: small
mini_office_2 →  Office name: Office 2, Location: Los Angeles, Size: medium

mini_office_1 →  Office name: Office 1, Location: Chicago, Size: small
mini_office_2 →  Office name: Office 2, Location: Los Angeles, Size: medium



# 04 NumPy and Basic Pandas
## NumPy

In [100]:
import numpy as np
# example of numpy arrays and functions
array_1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("array_1 = \n", array_1)
print("array_1.shape = ", array_1.shape) # the shape of the array number of rows, columns
print("array_1.ndim = ", array_1.ndim) # the number of dimensions of the array
print("array_1.size = ", array_1.size) # the number of elements in the array
print("array_1.T = \n", array_1.T) # transpose the array
# Array Functions
print("np.sum(array_1) = ", np.sum(array_1))
print("np.sum(array_1, axis=0) = \n", np.sum(array_1, axis=0)) # sum the rows
print("np.log(array_1) = \n", np.log(array_1)) # log of each element
print("np.exp(array_1) = \n", np.exp(array_1)) # exp of each element

array_1 = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array_1.shape =  (4, 3)
array_1.ndim =  2
array_1.size =  12
array_1.T = 
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
np.sum(array_1) =  78
np.sum(array_1, axis=0) = 
 [22 26 30]
np.log(array_1) = 
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]
 [2.30258509 2.39789527 2.48490665]]
np.exp(array_1) = 
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]


## Pandas

In [114]:
import pandas as pd
# example of pandas series
names = ['Bob', 'Jessica', 'Mary', 'John', 'Mel']
s = pd.Series(names)
print("s = \n", s)
# index change
identity_num = [12436,64813,15486,36874,93654]
s = pd.Series(names, index=identity_num)
print("s = \n", s)

# series functions
print("s.index = ", s.index) # the index of the series
print("s.values = ", s.values) # the values of the series
print("s.name = ", s.name) # the name of the series
s.name = "C.C Name"
print("s.name = ", s.name)
print()
print("s.describe() = \n", s.describe()) # describe the series

s = 
 0        Bob
1    Jessica
2       Mary
3       John
4        Mel
dtype: object
s = 
 12436        Bob
64813    Jessica
15486       Mary
36874       John
93654        Mel
dtype: object
s.index =  Int64Index([12436, 64813, 15486, 36874, 93654], dtype='int64')
s.values =  ['Bob' 'Jessica' 'Mary' 'John' 'Mel']
s.name =  None
s.name =  C.C Name

s.describe() = 
 count       5
unique      5
top       Bob
freq        1
Name: C.C Name, dtype: object


In [116]:
# pandas series numerical functions
s = pd.Series([1246,4813,1548,3687,9365], name='Nums')
print("s = \n", s)
print("s.max() = ", s.max())
print("s.min() = ", s.min())
print("s.describe() = \n", s.describe())

s = 
 0    1246
1    4813
2    1548
3    3687
4    9365
Name: Nums, dtype: int64
s.max() =  9365
s.min() =  1246
s.describe() = 
 count       5.000000
mean     4131.800000
std      3280.705976
min      1246.000000
25%      1548.000000
50%      3687.000000
75%      4813.000000
max      9365.000000
Name: Nums, dtype: float64


# 05 Pandas-Resampling and DataFrame
## Fetching Data

In [117]:
import yfinance as yf

aapl = yf.Ticker("AAPL") # create a ticker object
print("aapl.info = \n", aapl.info) # get the ticker information
print("aapl.history(period='1d', interval='1m') = \n", aapl.history(period='1d', interval='1m')) # get the historical data

aapl.info = 
 {'zip': '95014', 'sector': 'Technology', 'fullTimeEmployees': 100000, 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch, and other Apple-branded and third-party accessories. It also provides AppleCare support services; cloud services store services; and operates various platforms, including the App Store, that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Music, which offers users a curated listening experience with 

## Resampling

In [122]:
# resampling
aapl = yf.Ticker("AAPL")
print("aapl.history(period='1d', interval='1m').resample('1d').mean() = \n", aapl.history(period='1d', interval='1m').resample('1d').mean()) # resample the data to daily


aapl.history(period='1d', interval='1m').resample('1d').mean() = 
                                  Open        High         Low       Close  \
Datetime                                                                    
2021-10-29 00:00:00-04:00  148.482287  148.549419  148.421998  148.491042   

                                  Volume  Dividends  Stock Splits  
Datetime                                                           
2021-10-29 00:00:00-04:00  277229.230769        0.0           0.0  


## DataFrame

In [123]:
# example of pandas dataframe
data = {'Name': ['Bob', 'Jessica', 'Mary', 'John', 'Mel'],
        'Location': ['New York', 'New York', 'New York', 'New York', 'New York'],
        'Age': [22, 21, 23, 23, 22]}
df = pd.DataFrame(data)
print("df = \n", df)
print("df.index = ", df.index) # the index of the dataframe
print("df.columns = ", df.columns) # the columns of the dataframe
print("df.values = \n", df.values) # the values of the dataframe
print("df.T = \n", df.T) # transpose the dataframe

df = 
       Name  Location  Age
0      Bob  New York   22
1  Jessica  New York   21
2     Mary  New York   23
3     John  New York   23
4      Mel  New York   22
df.index =  RangeIndex(start=0, stop=5, step=1)
df.columns =  Index(['Name', 'Location', 'Age'], dtype='object')
df.values = 
 [['Bob' 'New York' 22]
 ['Jessica' 'New York' 21]
 ['Mary' 'New York' 23]
 ['John' 'New York' 23]
 ['Mel' 'New York' 22]]
df.T = 
                  0         1         2         3         4
Name           Bob   Jessica      Mary      John       Mel
Location  New York  New York  New York  New York  New York
Age             22        21        23        23        22
